from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json

def connectionDB():
  cloud_config= {
    'secure_connect_bundle': 'app/secure-connect-cassandra.zip'
  }
  # This secure connect bundle is autogenerated when you download your SCB, 
  # if yours is different update the file name below

  # This token JSON file is autogenerated when you download your token, 
  # if yours is different update the file name below
  with open("app/cassandra-token.json") as f:
      secrets = json.load(f)

  CLIENT_ID = secrets["clientId"]
  CLIENT_SECRET = secrets["secret"]
  auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
  cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
  session = cluster.connect('movies_app')
  
  # row = session.execute("select release_version from system.local").one()

  if session:
    # print(row[0])
    return [cluster, session]
  else:
    print("An error occurred.")